/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as LandingRouteImport } from './app/routes/landing'
import { Route as AppRouteRouteImport } from './app/routes/app/route'
import { Route as AuthRouteRouteImport } from './app/routes/_auth/route'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AppIndexRouteImport } from './app/routes/app/index'
import { Route as AppDashboardRouteImport } from './app/routes/app/dashboard'
import { Route as AuthSignupRouteImport } from './app/routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './app/routes/_auth/signin'
import { Route as AppVocabularyRouteRouteImport } from './app/routes/app/vocabulary/route'
import { Route as AppQuizIndexRouteImport } from './app/routes/app/quiz/index'
import { Route as AppMockTestIndexRouteImport } from './app/routes/app/mock-test/index'
import { Route as AppFlashcardIndexRouteImport } from './app/routes/app/flashcard/index'
import { Route as AppQuizQuizIdRouteImport } from './app/routes/app/quiz/$quizId'
import { Route as AppMockTestWritingRouteImport } from './app/routes/app/mock-test/writing'
import { Route as AppMockTestSpeakingRouteImport } from './app/routes/app/mock-test/speaking'
import { Route as AppMockTestReadingRouteImport } from './app/routes/app/mock-test/reading'
import { Route as AppMockTestListeningRouteImport } from './app/routes/app/mock-test/listening'
import { Route as AppFlashcardDeckIdIndexRouteImport } from './app/routes/app/flashcard/$deckId/index'
import { Route as AppFlashcardDeckIdStudyRouteImport } from './app/routes/app/flashcard/$deckId/study'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppVocabularyRouteRoute = AppVocabularyRouteRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuizIndexRoute = AppQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMockTestIndexRoute = AppMockTestIndexRouteImport.update({
  id: '/mock-test/',
  path: '/mock-test/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFlashcardIndexRoute = AppFlashcardIndexRouteImport.update({
  id: '/flashcard/',
  path: '/flashcard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuizQuizIdRoute = AppQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMockTestWritingRoute = AppMockTestWritingRouteImport.update({
  id: '/mock-test/writing',
  path: '/mock-test/writing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMockTestSpeakingRoute = AppMockTestSpeakingRouteImport.update({
  id: '/mock-test/speaking',
  path: '/mock-test/speaking',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMockTestReadingRoute = AppMockTestReadingRouteImport.update({
  id: '/mock-test/reading',
  path: '/mock-test/reading',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMockTestListeningRoute = AppMockTestListeningRouteImport.update({
  id: '/mock-test/listening',
  path: '/mock-test/listening',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFlashcardDeckIdIndexRoute = AppFlashcardDeckIdIndexRouteImport.update({
  id: '/flashcard/$deckId/',
  path: '/flashcard/$deckId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFlashcardDeckIdStudyRoute = AppFlashcardDeckIdStudyRouteImport.update({
  id: '/flashcard/$deckId/study',
  path: '/flashcard/$deckId/study',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/app/vocabulary': typeof AppVocabularyRouteRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/app/mock-test/listening': typeof AppMockTestListeningRoute
  '/app/mock-test/reading': typeof AppMockTestReadingRoute
  '/app/mock-test/speaking': typeof AppMockTestSpeakingRoute
  '/app/mock-test/writing': typeof AppMockTestWritingRoute
  '/app/quiz/$quizId': typeof AppQuizQuizIdRoute
  '/app/flashcard': typeof AppFlashcardIndexRoute
  '/app/mock-test': typeof AppMockTestIndexRoute
  '/app/quiz': typeof AppQuizIndexRoute
  '/app/flashcard/$deckId/study': typeof AppFlashcardDeckIdStudyRoute
  '/app/flashcard/$deckId': typeof AppFlashcardDeckIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/app/vocabulary': typeof AppVocabularyRouteRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app': typeof AppIndexRoute
  '/app/mock-test/listening': typeof AppMockTestListeningRoute
  '/app/mock-test/reading': typeof AppMockTestReadingRoute
  '/app/mock-test/speaking': typeof AppMockTestSpeakingRoute
  '/app/mock-test/writing': typeof AppMockTestWritingRoute
  '/app/quiz/$quizId': typeof AppQuizQuizIdRoute
  '/app/flashcard': typeof AppFlashcardIndexRoute
  '/app/mock-test': typeof AppMockTestIndexRoute
  '/app/quiz': typeof AppQuizIndexRoute
  '/app/flashcard/$deckId/study': typeof AppFlashcardDeckIdStudyRoute
  '/app/flashcard/$deckId': typeof AppFlashcardDeckIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/app/vocabulary': typeof AppVocabularyRouteRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/app/mock-test/listening': typeof AppMockTestListeningRoute
  '/app/mock-test/reading': typeof AppMockTestReadingRoute
  '/app/mock-test/speaking': typeof AppMockTestSpeakingRoute
  '/app/mock-test/writing': typeof AppMockTestWritingRoute
  '/app/quiz/$quizId': typeof AppQuizQuizIdRoute
  '/app/flashcard/': typeof AppFlashcardIndexRoute
  '/app/mock-test/': typeof AppMockTestIndexRoute
  '/app/quiz/': typeof AppQuizIndexRoute
  '/app/flashcard/$deckId/study': typeof AppFlashcardDeckIdStudyRoute
  '/app/flashcard/$deckId/': typeof AppFlashcardDeckIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/landing'
    | '/app/vocabulary'
    | '/signin'
    | '/signup'
    | '/app/dashboard'
    | '/app/'
    | '/app/mock-test/listening'
    | '/app/mock-test/reading'
    | '/app/mock-test/speaking'
    | '/app/mock-test/writing'
    | '/app/quiz/$quizId'
    | '/app/flashcard'
    | '/app/mock-test'
    | '/app/quiz'
    | '/app/flashcard/$deckId/study'
    | '/app/flashcard/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/app/vocabulary'
    | '/signin'
    | '/signup'
    | '/app/dashboard'
    | '/app'
    | '/app/mock-test/listening'
    | '/app/mock-test/reading'
    | '/app/mock-test/speaking'
    | '/app/mock-test/writing'
    | '/app/quiz/$quizId'
    | '/app/flashcard'
    | '/app/mock-test'
    | '/app/quiz'
    | '/app/flashcard/$deckId/study'
    | '/app/flashcard/$deckId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/landing'
    | '/app/vocabulary'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/app/dashboard'
    | '/app/'
    | '/app/mock-test/listening'
    | '/app/mock-test/reading'
    | '/app/mock-test/speaking'
    | '/app/mock-test/writing'
    | '/app/quiz/$quizId'
    | '/app/flashcard/'
    | '/app/mock-test/'
    | '/app/quiz/'
    | '/app/flashcard/$deckId/study'
    | '/app/flashcard/$deckId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LandingRoute: typeof LandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/vocabulary': {
      id: '/app/vocabulary'
      path: '/vocabulary'
      fullPath: '/app/vocabulary'
      preLoaderRoute: typeof AppVocabularyRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/quiz/': {
      id: '/app/quiz/'
      path: '/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mock-test/': {
      id: '/app/mock-test/'
      path: '/mock-test'
      fullPath: '/app/mock-test'
      preLoaderRoute: typeof AppMockTestIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/flashcard/': {
      id: '/app/flashcard/'
      path: '/flashcard'
      fullPath: '/app/flashcard'
      preLoaderRoute: typeof AppFlashcardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/quiz/$quizId': {
      id: '/app/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/app/quiz/$quizId'
      preLoaderRoute: typeof AppQuizQuizIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mock-test/writing': {
      id: '/app/mock-test/writing'
      path: '/mock-test/writing'
      fullPath: '/app/mock-test/writing'
      preLoaderRoute: typeof AppMockTestWritingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mock-test/speaking': {
      id: '/app/mock-test/speaking'
      path: '/mock-test/speaking'
      fullPath: '/app/mock-test/speaking'
      preLoaderRoute: typeof AppMockTestSpeakingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mock-test/reading': {
      id: '/app/mock-test/reading'
      path: '/mock-test/reading'
      fullPath: '/app/mock-test/reading'
      preLoaderRoute: typeof AppMockTestReadingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mock-test/listening': {
      id: '/app/mock-test/listening'
      path: '/mock-test/listening'
      fullPath: '/app/mock-test/listening'
      preLoaderRoute: typeof AppMockTestListeningRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/flashcard/$deckId/': {
      id: '/app/flashcard/$deckId/'
      path: '/flashcard/$deckId'
      fullPath: '/app/flashcard/$deckId'
      preLoaderRoute: typeof AppFlashcardDeckIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/flashcard/$deckId/study': {
      id: '/app/flashcard/$deckId/study'
      path: '/flashcard/$deckId/study'
      fullPath: '/app/flashcard/$deckId/study'
      preLoaderRoute: typeof AppFlashcardDeckIdStudyRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppVocabularyRouteRoute: typeof AppVocabularyRouteRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMockTestListeningRoute: typeof AppMockTestListeningRoute
  AppMockTestReadingRoute: typeof AppMockTestReadingRoute
  AppMockTestSpeakingRoute: typeof AppMockTestSpeakingRoute
  AppMockTestWritingRoute: typeof AppMockTestWritingRoute
  AppQuizQuizIdRoute: typeof AppQuizQuizIdRoute
  AppFlashcardIndexRoute: typeof AppFlashcardIndexRoute
  AppMockTestIndexRoute: typeof AppMockTestIndexRoute
  AppQuizIndexRoute: typeof AppQuizIndexRoute
  AppFlashcardDeckIdStudyRoute: typeof AppFlashcardDeckIdStudyRoute
  AppFlashcardDeckIdIndexRoute: typeof AppFlashcardDeckIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppVocabularyRouteRoute: AppVocabularyRouteRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppMockTestListeningRoute: AppMockTestListeningRoute,
  AppMockTestReadingRoute: AppMockTestReadingRoute,
  AppMockTestSpeakingRoute: AppMockTestSpeakingRoute,
  AppMockTestWritingRoute: AppMockTestWritingRoute,
  AppQuizQuizIdRoute: AppQuizQuizIdRoute,
  AppFlashcardIndexRoute: AppFlashcardIndexRoute,
  AppMockTestIndexRoute: AppMockTestIndexRoute,
  AppQuizIndexRoute: AppQuizIndexRoute,
  AppFlashcardDeckIdStudyRoute: AppFlashcardDeckIdStudyRoute,
  AppFlashcardDeckIdIndexRoute: AppFlashcardDeckIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  LandingRoute: LandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
