/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as LandingRouteImport } from './app/routes/landing'
import { Route as AppRouteRouteImport } from './app/routes/app/route'
import { Route as AuthRouteRouteImport } from './app/routes/_auth/route'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AppIndexRouteImport } from './app/routes/app/index'
import { Route as AppQuizRouteImport } from './app/routes/app/quiz'
import { Route as AppDashboardRouteImport } from './app/routes/app/dashboard'
import { Route as AuthSignupRouteImport } from './app/routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './app/routes/_auth/signin'
import { Route as AppVocabularyRouteRouteImport } from './app/routes/app/vocabulary/route'
import { Route as AppFlashcardIndexRouteImport } from './app/routes/app/flashcard/index'
import { Route as AppFlashcardDeckIdRouteImport } from './app/routes/app/flashcard/$deckId'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppVocabularyRouteRoute = AppVocabularyRouteRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFlashcardIndexRoute = AppFlashcardIndexRouteImport.update({
  id: '/flashcard/',
  path: '/flashcard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFlashcardDeckIdRoute = AppFlashcardDeckIdRouteImport.update({
  id: '/flashcard/$deckId',
  path: '/flashcard/$deckId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/app/vocabulary': typeof AppVocabularyRouteRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/': typeof AppIndexRoute
  '/app/flashcard/$deckId': typeof AppFlashcardDeckIdRoute
  '/app/flashcard': typeof AppFlashcardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/app/vocabulary': typeof AppVocabularyRouteRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/quiz': typeof AppQuizRoute
  '/app': typeof AppIndexRoute
  '/app/flashcard/$deckId': typeof AppFlashcardDeckIdRoute
  '/app/flashcard': typeof AppFlashcardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/app/vocabulary': typeof AppVocabularyRouteRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/': typeof AppIndexRoute
  '/app/flashcard/$deckId': typeof AppFlashcardDeckIdRoute
  '/app/flashcard/': typeof AppFlashcardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/landing'
    | '/app/vocabulary'
    | '/signin'
    | '/signup'
    | '/app/dashboard'
    | '/app/quiz'
    | '/app/'
    | '/app/flashcard/$deckId'
    | '/app/flashcard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/app/vocabulary'
    | '/signin'
    | '/signup'
    | '/app/dashboard'
    | '/app/quiz'
    | '/app'
    | '/app/flashcard/$deckId'
    | '/app/flashcard'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/landing'
    | '/app/vocabulary'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/app/dashboard'
    | '/app/quiz'
    | '/app/'
    | '/app/flashcard/$deckId'
    | '/app/flashcard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LandingRoute: typeof LandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/quiz': {
      id: '/app/quiz'
      path: '/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/vocabulary': {
      id: '/app/vocabulary'
      path: '/vocabulary'
      fullPath: '/app/vocabulary'
      preLoaderRoute: typeof AppVocabularyRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/flashcard/': {
      id: '/app/flashcard/'
      path: '/flashcard'
      fullPath: '/app/flashcard'
      preLoaderRoute: typeof AppFlashcardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/flashcard/$deckId': {
      id: '/app/flashcard/$deckId'
      path: '/flashcard/$deckId'
      fullPath: '/app/flashcard/$deckId'
      preLoaderRoute: typeof AppFlashcardDeckIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppVocabularyRouteRoute: typeof AppVocabularyRouteRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppQuizRoute: typeof AppQuizRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFlashcardDeckIdRoute: typeof AppFlashcardDeckIdRoute
  AppFlashcardIndexRoute: typeof AppFlashcardIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppVocabularyRouteRoute: AppVocabularyRouteRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppQuizRoute: AppQuizRoute,
  AppIndexRoute: AppIndexRoute,
  AppFlashcardDeckIdRoute: AppFlashcardDeckIdRoute,
  AppFlashcardIndexRoute: AppFlashcardIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  LandingRoute: LandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
